workflows:
  build-macos-dmg-only:
    name: Build macOS dmg for 越进创客
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean & get dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Build macOS App (for DMG)
        script: |
          flutter build macos --release

      - name: Create .dmg (未签名)
        script: |
          APP_NAME="越进创客"
          BUILD_PATH="build/macos/Build/Products/Release"
          ORIGINAL_APP_PATH="${BUILD_PATH}/demo.app"
          TEMP_APP_PATH="dmg_temp/${APP_NAME}.app"
          DMG_NAME="${APP_NAME}_unsigned.dmg"

          echo "🛠 检查构建产物是否存在：$ORIGINAL_APP_PATH"
          if [ ! -d "$ORIGINAL_APP_PATH" ]; then
            echo "❌ 未找到 $ORIGINAL_APP_PATH"
            ls -lh ${BUILD_PATH}
            exit 1
          fi

          mkdir -p dmg_temp
          cp -R "$ORIGINAL_APP_PATH" "$TEMP_APP_PATH"

          hdiutil create "$DMG_NAME" -volname "$APP_NAME" -srcfolder dmg_temp -ov -format UDZO

          # 可选：删除中间产物
          rm -rf dmg_temp
          rm -rf "$ORIGINAL_APP_PATH"

      - name: Output artifact
        script: |
          echo "✅ 只输出 .dmg 文件："
          ls -lh 越进创客_unsigned.dmg

    artifacts:
      - 越进创客_unsigned.dmg
